### PR TITLE
Add the ability to ignore values

### PR DESCRIPTION
**Pull request by yehiyam**
implements #10 
Adds a special key (`+doc-gen:ignore`) to allow ignoring a section in the values.yaml file.
example:
```yaml
platform:
  # Set true, if installed in OpenShift
  openshift: false

toIgnore: # +doc-gen:ignore
  foo: true
toIgnore2: false # +doc-gen:ignore
```

### CODE REVIEW

**Comment by yehiyam** [comment]
@tamalsaha did you have a chance to look over the PR?

**Comment by chgl** [comment]
Would love to use this feature as well! Looks like @yehiyam you will need to sign the CLA. Are there any other blockers @tamalsaha ?

**Comment by tamalsaha** [comment]
No.

**Comment by yehiyam** [comment]
@tamalsaha Signed the CLA

**Comment by tamalsaha** [comment]
Thanks, @yehiyam !

**Comment by tamalsaha** [comment]
Released https://github.com/kubepack/chart-doc-gen/releases/tag/v0.3.4

**Pull request merged**
