### PR TITLE
Show multi-value lines inside <code> block #31

### LINKED ISSUE #31: Multiline values are currently broken
the go package `github.com/olekukonko/tablewriter` handles newlines in strings a bit weird. It creates new table rows for each newline.

This kills the preview for multiline yaml values e.g:

```
someKey: |
   this is a
   multiline
   value
```

because it creates a table looking like

| a             | b               | c            |
|-------------|---------------|-------------|
|someKey |                  | |             |
|                |                  | this is a  |
|                |                  | multiline |
|                |                  | value     |

instead of how the table should actually look like

| a             | b               | c            |
|-------------|---------------|-------------|
|someKey |                  | &#124;<br>this is a<br>multiline<br>value  |

### PR DESCRIPTION
**Pull request by cstruck**

### CODE REVIEW

**Review by lftgl — APPROVED** [review]
well done, hope it works now

**Review by lftgl — APPROVED** [review]

**Review by zerofudge — APPROVED** [review]

**Comment by cstruck** [comment]
any updates here?

**Comment by tamalsaha** [comment]
@cstruck, can you please sign the CLA?

**Review by FaniD — APPROVED** [review]

**Comment by FaniD** [comment]
Can this be merged? We've been working with this patch quite some time, works as expected.

**Comment by tamalsaha** [comment]
Released https://github.com/kubepack/chart-doc-gen/releases/tag/v0.4.4

**Pull request merged**
